---
- name: ensure development tools are installed
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ spack_ubuntu_deps }}"

- name: ensure install directory exists
  file:
    path: "{{ spack_install_dir }}"
    owner: "{{ spack_user }}"
    group: "{{ spack_group }}"
    mode: "0755"
    state: "directory"

- name: clone spack repository
  git:
    repo: "{{ spack_repo }}"
    dest: "{{ spack_install_dir }}"
    version: "{{ spack_version }}"

- name: source spack environment once for initialization
  shell: |
      . /etc/profile.d/z00_spack.sh

- name: build spack packages
  shell: |
      . /etc/profile.d/z00_spack.sh &&
      spack install {{ item }}
  with_items: "{{ spack_default_packages }}"
  when: spack_build_packages
