---
spack_repo: "https://github.com/spack/spack.git"
spack_install_dir: "/sw/spack"
spack_version: "v0.19.1"
spack_user: "root"
spack_group: "root"

spack_ubuntu_deps:
- "gcc-7"
- "gfortran-7"
- "make"
- "git"

spack_build_packages: false
spack_default_packages:
