---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - numactl
  when: ansible_distribution == 'Ubuntu'

- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - psmisc
    - numactl
  when: ansible_os_family == "RedHat"

- name: add cgroups to grub options
  lineinfile:
    # Slurm does not yet support cgroups v2.
    dest: /etc/default/grub
    insertafter: '^GRUB_CMDLINE_LINUX=[^\\$]'
    line: 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} systemd.unified_cgroup_hierarchy=false systemd.legacy_systemd_cgroup_controller=false cgroup_enable=memory swapaccount=1"'
  register: update_grub

- name: update grub
  block:
    - name: update grub
      command: update-grub
      register: update_grub_cmd
      changed_when: update_grub_cmd.rc == 0
    - name: reboot after updating grub config
      reboot:
        reboot_timeout: "{{ slurm_node_reboot_timeout }}"
  when: update_grub.changed and ansible_os_family == "Debian"

- name: update grub
  block:
    - name: update grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      register: grub2_mkconfig_cmd
      changed_when: grub2_mkconfig_cmd.rc == 0
    - name: reboot after updating grub config
      reboot:
        reboot_timeout: "{{ slurm_node_reboot_timeout }}"
  when: update_grub.changed and ansible_os_family == "RedHat"

- name: create sysconfig dir
  file:
    path: "{{ slurm_sysconf_dir }}"
    state: directory
    owner: root
    mode: 0755

- name: create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    mode: 0755
  with_items:
    - "{{ slurm_config_dir }}"
    - "{{ slurm_config_dir }}/shared"
    - "{{ slurm_config_dir }}/shared/bin"
    - /var/log/slurm
    - /var/spool/slurm/d
  tags:
    - prolog
    - epilog

- name: configure slurmd for pmix
  blockinfile:
    path: "{{ slurm_sysconf_dir }}/slurmd"
    create: yes
    mode: "0644"
    block: |
      PMIX_MCA_ptl=^usock
      PMIX_MCA_psec=none
      PMIX_SYSTEM_TMPDIR=/var/empty
      PMIX_MCA_gds=hash
  notify: restart slurmd
  tags: config

- name: copy shared scripts
  template:
    src: "{{ item }}"
    dest: "{{ slurm_config_dir }}/shared/bin/"
    mode: 0755
  with_fileglob:
    - templates/etc/slurm/shared/bin/*
  tags:
    - prolog
    - epilog

- name: include prolog/epilog
  include: prolog_epilog.yml
  when: slurm_enable_prolog_epilog

- name: configure slurm.conf
  template:
    src: "{{ slurm_conf_template }}"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    mode: "0644"
  when: not slurm_conf_symlink
  notify:
  - restart slurmd
  tags:
  - config

- name: configure slurm.conf by symbolic link
  file:
    path: "{{ slurm_config_dir }}/slurm.conf"
    state: link
    src: "{{ slurmctl_config_dir }}/slurm.conf"
    force: yes
  when: slurm_conf_symlink
  notify:
  - restart slurmd
  tags:
  - config

- name: configure cgroup.conf
  template:
    src: "{{ slurm_cgroup_conf_template }}"
    dest: "{{ slurm_config_dir }}/cgroup.conf"
    mode: "0644"
  notify:
  - restart slurmd
  tags:
  - config

- name: configure gres.conf
  template:
    src: "{{ slurm_gres_conf_template }}"
    dest: "{{ slurm_config_dir }}/gres.conf"
    mode: "0644"
  notify:
  - restart slurmd
  tags:
  - config

- name: start slurmd
  systemd:
    name: slurmd
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: install /etc/login.local.user.allowed
  template:
    src: etc/login.local.user.allowed
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - "{{ slurm_config_dir }}/login.local.user.allowed.backup"
    - /etc/login.local.user.allowed
  tags:
    - login.local.user.allowed

- name: install /etc/login.local.group.allowed
  template:
    src: etc/login.local.group.allowed
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - "{{ slurm_config_dir }}/login.local.group.allowed.backup"
    - /etc/login.local.group.allowed
  tags:
    - login.local.group.allowed

- name: configure /etc/pam.d/sshd to restrict node access without jobs
  blockinfile:
    path: /etc/pam.d/sshd
    block: |
      -account required {{ slurm_pam_lib_dir }}/pam_slurm_adopt.so action_no_jobs=ignore
      -account sufficient pam_listfile.so item=user sense=allow file=/etc/login.local.user.allowed
      -account sufficient pam_listfile.so onerr=fail item=group sense=allow file=/etc/login.local.group.allowed
      -account required {{ slurm_pam_lib_dir }}/pam_slurm_adopt.so
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ansible-role-slurm)"
  tags:
    - config
  when:
  - slurm_enable_pam_slurm_adopt
  - slurm_restrict_node_access

- name: configure /etc/pam.d/sshd to adopt processes but not otherwise deny access
  blockinfile:
    path: /etc/pam.d/sshd
    block: |
      -account sufficient {{ slurm_pam_lib_dir }}/pam_slurm_adopt.so action_no_jobs=ignore
      -account sufficient pam_listfile.so item=user sense=allow file=/etc/login.local.user.allowed
      -account sufficient pam_listfile.so onerr=fail item=group sense=allow file=/etc/login.local.group.allowed
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (ansible-role-slurm)"
  tags:
    - config
  when:
  - slurm_enable_pam_slurm_adopt
  - not slurm_restrict_node_access

- name: comment out pam_systemd.so as it conflicts with pam_slurm_adapt.so, see https://slurm.schedmd.com/pam_slurm_adopt.html
  replace:
    path: /etc/pam.d/common-session
    regexp: '^([^#].*pam_systemd.so.*)'
    replace: '# \1 # ANSIBLE MANAGED (ansible-role-slurm)'
  when:
  - ansible_distribution == 'Ubuntu'
  - slurm_enable_pam_slurm_adopt
  tags:
    - config

- name: comment out pam_systemd.so in RHEL as it conflicts with pam_slurm_adapt.so, see https://slurm.schedmd.com/pam_slurm_adopt.html
  replace:
    path: /etc/pam.d/password-auth
    regexp: '^([^#].*pam_systemd.so.*)'
    replace: '# \1 # ANSIBLE MANAGED (ansible-role-slurm)'
  when:
  - ansible_os_family == "RedHat"
  - slurm_enable_pam_slurm_adopt
  tags:
    - config
