#
# ansible role to install lmod:
#
---
- name: "install packages"
  become: yes
  apt:
    name:
    - bash
    - tcsh
    - zsh
    - lmod
    state: present
  when: ansible_os_family == "Debian"

- name: "mkdir software path"
  become: yes
  file: path={{ sm_software_path }} state=directory

- name: "mkdir module path"
  become: yes
  file: path={{ sm_module_path }} state=directory 

- name: "configure sh profile"
  become: yes
  template:
    src: templates/z00_lmod.sh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: 0777
  tags:
    - configuration

- name: "configure csh profile"
  become: yes
  template:
    src: templates/z00_lmod.csh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: 0777
  tags:
    - configuration

- name: "configure zsh profile"
  become: yes
  template:
    src: templates/z00_lmod.zsh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: 0777
  tags:
    - configuration

- name: source zsh profile on login
  lineinfile:
    dest: /etc/zsh/zprofile
    insertafter: EOF
    line: 'source /etc/profile.d/z00_lmod.zsh'
  register: update_zsh_lmod


# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891541
- name: "bugfix for lmod posix_c"
  become: yes
  shell: |
    ln -s -f /usr/lib/x86_64-linux-gnu/lua/5.1/posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.1/posix.so
    ln -s -f /usr/lib/x86_64-linux-gnu/lua/5.2/posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.2/posix.so
    ln -s -f /usr/lib/x86_64-linux-gnu/lua/5.3/posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.3/posix.so
  when: 
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: "unset previous lmod setup"
  shell: unset MODULEPATH_ROOT
  args:
    executable: /bin/bash

- name: "unset previous lmod setup"
  shell: unsetenv MODULEPATH_ROOT
  args:
    executable: /bin/csh

- name: "auto load lmod bash"
  shell: . /etc/profile.d/z00_lmod.sh
  args:
    executable: /bin/bash

- name: "auto load lmod csh"
  shell: source /etc/profile.d/z00_lmod.csh
  args:
    executable: /bin/csh

- name: "auto load lmod zsh"
  shell: source /etc/profile.d/z00_lmod.zsh
  args:
    executable: /bin/zsh