- name: add projects to /etc/fstab
  blockinfile:
    dest: /etc/fstab
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    content: |
      {{ ansible_local['project_folders']['fstab'] }}
  register: update_fstab

- name: create mounts if they don't exist
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ ansible_local['project_folders']['folders'] }}"

- name: mount drives
  command: mount -a
  register: drives_mounted
