---
- hosts:  "{{ hostlist | default('slurm-login,slurm-node') }}"
  become: yes
  tasks:
    - name: Gather custom facts
      include_role:
        name: facts
    - name: Create mount points
      include_role:
        name: create-mounts
